version: '3'

services:


  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm run prisma
    networks: 
      - node-network
    tty: true
    environment:
        - DATABASE_URL=mysql://root:root@db:3306/nodedb
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  proxy:
    build:
      context: nginx
    container_name: proxy
    networks: 
      - node-network
    tty: true
    ports: 
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge